sudo: required
services:
  - docker


before_install:
  - docker build -t pr306500/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run pr306500/react-test  npm test -- --coverage

after_success:
  - docker build -t pr306500/multi-client ./client
  - docker build -t pr306500/multi-nginx  ./nginx
  - docker build -t pr306500/multi-server ./server
  - docker build -t pr306500/multi-worker ./worker

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push pr306500/multi-client
  - docker push pr306500/multi-nginx
  - docker push pr306500/multi-server
  - docker push pr306500/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "DockerReact-env-1"
  bucket_name: "elasticbeanstalk-us-east-2-570620410534"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY" 
