'version': '3'
'services':
   postgres:
     image: 'postgres:latest'
   redis:
     image: 'redis:latest'
   nginx:
     restart: always
     build:
      dockerfile: Dockerfile.dev
      context: ./nginx
     ports:
       - '3050:80'
   client:
      build:
       context: ./client
       dockerfile: Dockerfile.dev
      volumes:
       - /app/node_modules
       - ./client:/app
   api:
     build:
       context: ./server
       dockerfile: Dockerfile.dev
     volumes:
       - /app/node_modules
       - ./server:/app
     environment:
       - REDIS_HOST=redis
       - REDIS_PORT=6379
       - PGUSER=postgres
       - PGHOST=postgres
       - PGDATABASE=postgres
       - PGPASSWORD=postgres_password
       - PGPORT=5432
   worker:
      build:
       context: ./worker
       dockerfile: Dockerfile.dev
      volumes:
       - /app/node_modules
       - ./worker:/app